### ISSUE TITLE
did not find expected key while parsing a block mapping at line 6 column 3

### ISSUE THREAD

**Issue by felipecaldas** [scatterp/peatio#8] opened 2017-10-31 10:26 UTC
Hi scatterp,

Trying your fork and running the install1.sh. When it gets to this line:

`bundle exec rake db:setup`

I get this error:

```
docker@0e4b90510eea:~/peatio/current$ bundle exec rake db:setup
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3
/home/docker/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
/home/docker/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
/home/docker/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
/home/docker/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/docker/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/docker/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/docker/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/docker/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/docker/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:67:in `inherited'
/home/docker/peatio/current/config/application.rb:15:in `<module:Peatio>'
/home/docker/peatio/current/config/application.rb:14:in `<top (required)>'
/home/docker/peatio/current/Rakefile:5:in `require'
/home/docker/peatio/current/Rakefile:5:in `<top (required)>'
/home/docker/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/home/docker/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
docker@0e4b90510eea:~/peatio/current$

```

I am running this inside a Docker container.

Any idea what this might be?

Thanks!

**Comment by scatterp** [comment] 2017-11-01 10:36
yes you messed up on the config specifically its an error with a YML file you should check you are using latest code from me and also then verify the YML using https://codebeautify.org/yaml-validator
you are apparently looking for an error at line 6 column 3 you could run the command with the trace option which might make it easier to see whats going wrong

**Comment by scatterp** [comment] 2017-11-01 10:36
please share your docker stuff when its done

**Comment by felipecaldas** [comment] 2017-11-01 10:38
Thanks.
Probably did something wrong when editing the yml files.

I'll definitely share once I have a docker container running properly!

**Comment by scatterp** [comment] 2017-11-01 13:54
please close this if the issue is resolved or let me know if you need more help

**Closed** 2017-11-04 10:17 UTC
